const names = "Frontend Deverloper";
const job = "deverloper";
const authStr = `my name is ${names} i am ${job}`;
// console.log(authStr);
// console.log(authStr.length);
// console.log(names.split(" "));
// console.log(names.split(""));
//console.log(authStr.startsWith("my"));
// console.log(names.includes("end"));
// console.log(names.indexOf("D"));
// console.log(names.replace("Deverloper","Designer"));
// console.log(names.repeat(5));
// console.log(names.slice(0,7));
// console.log(names.trim());
// console.log(names.charAt(5));
console.log(names.substr(1,10));
console.log(names.substring(1,9));