const names = "Fontend Deverloper";
const job = "deverloper";
const authStr = `my name is ${names} i am ${job}`;
// console.log(authStr);
// console.log(authStr.length);
// console.log(names.split(" "));
// console.log(names.split(""));
//console.log(authStr.startsWith("my"));
console.log(names.includes("end"));
console.log(names.indexOf("D"));